on:
  workflow_call:

jobs:
  setup:
    name: Prepare build context
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Docker BuildX
        uses: docker/setup-buildx-action@v2

      - name: Build WordPress image
        uses: docker/build-push-action@v3
        with:
          context: .docker
          file: .docker/wordpress.Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          pull: true
          load: true

  build_composer_prod:
    name: Add composer files
    runs-on: ubuntu-latest
    needs:
      - setup
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Docker BuildX
        uses: docker/setup-buildx-action@v2

      - name: Build WordPress image
        uses: docker/build-push-action@v3
        with:
          context: .docker
          file: .docker/wordpress.Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          pull: true
          load: true

      - name: Install PHP dependencies
        run: >-
          docker-compose 
          run 
          -u root:root 
          --no-deps
          wordpress 
          composer 
          --working-dir=wp-content/plugins/collectme 
          --no-interaction 
          install 
          --no-dev 
          --no-progress

      - name: Store vendor files
        uses: actions/upload-artifact@v3
        with:
          name: vendor-prod
          path: vendor

  build_js_prod:
    name: Add js files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate models
        run: >-
          docker-compose 
          run 
          -u root:root 
          --no-deps
          swagger-codegen 
          generate 
          -i /tmp/swagger/input/rest-api.yaml 
          -o /tmp/swagger/output 
          -l typescript-axios
          &&
          sudo chown -R $(id -u):$(id -g) gen
          &&
          sed -i '/import type/! s/import /import type /g' gen/models/*.ts
          &&
          sed -i -r 's/(\s)Date(\s)/\1string\2/g' gen/models/*.ts
          &&
          rsync -av --delete gen/models/ app/src/models/generated

      - name: Install JS dependencies
        run: >-
          docker-compose 
          run 
          -u root:root 
          --no-deps
          node 
          yarn 
          --no-progress 
          --non-interactive
          install
          --frozen-lockfile

      - name: Build JS files
        run: >-
          docker-compose 
          run 
          -u root:root 
          --no-deps
          node 
          yarn 
          --no-progress 
          --non-interactive
          run
          build-only

      - name: Store generated plugin assets
        uses: actions/upload-artifact@v3
        with:
          name: dist-prod
          path: dist

  build_pot:
    name: Add pot file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate translation template
        run: >-
          docker-compose 
          run 
          -u root:root
          --no-deps
          wordpress 
          bash 
          -c 'XDEBUG_MODE=off php -d memory_limit=1G $(which wp) --allow-root i18n make-pot wp-content/plugins/collectme/ wp-content/plugins/collectme/languages/collectme.pot --slug=collectme --domain=collectme --exclude=tmp,vendor --skip-js --skip-block-json --skip-theme-json'

      - name: Store generated plugin assets
        uses: actions/upload-artifact@v3
        with:
          name: pot
          path: languages/collectme.pot