on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/build.yml

  l10n:
    uses: ./.github/workflows/l10n.yml
    secrets:
      CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
      CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

  deploy:
    name: Prepare release
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get vendor files
        uses: actions/download-artifact@v3
        with:
          name: vendor-prod
          path: vendor

      - name: Get dist files
        uses: actions/download-artifact@v3
        with:
          name: dist-prod
          path: dist

      - name: Package files
        run: |
          mkdir /tmp/collectme
          rsync -av --exclude=index.html --exclude=favicon.ico ./dist /tmp/collectme
          rsync -av ./languages /tmp/collectme
          rsync -av ./src /tmp/collectme
          mkdir /tmp/collectme/tmp
          rsync -av ./vendor /tmp/collectme
          rsync -av ./views /tmp/collectme
          cp ./collectme.php /tmp/collectme
          cp ./dependency-config.php /tmp/collectme
          echo "See ${{ github.server_url }}/${{ github.repository }}" > /tmp/collectme/readme.txt
          cd /tmp
          zip -r collectme.zip collectme

      - name: Parse version number
        run: |
          echo "VERSION=$(sed '/^\s*\*\s*Version:/! d; s/^\s*\*\s*Version:\s*//; s/\s*$//' collectme.php)" >> $GITHUB_ENV

      - name: Prepare release
        uses: softprops/action-gh-release@v1
        with:
          files: /tmp/collectme.zip
          draft: true
#          generate_release_notes: true
          name: "${{ env.VERSION }}"