on:
  workflow_call:
    secrets:
      CROWDIN_PROJECT_ID:
        required: true
      CROWDIN_PERSONAL_TOKEN:
        required: true

jobs:
  template:
    name: L10N Sync with Crowdin
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Setup Docker BuildX
        uses: docker/setup-buildx-action@v2

      - name: Build WordPress image
        uses: docker/build-push-action@v3
        with:
          context: .docker
          file: .docker/wordpress.Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          pull: true
          load: true
          tags: grueneschweiz/collectme:latest

      - name: Generate translation template
        run: >-
          docker-compose 
          run 
          -u root:root
          --no-deps
          wordpress 
          bash 
          -c 'XDEBUG_MODE=off php -d memory_limit=1G $(which wp) --allow-root i18n make-pot wp-content/plugins/collectme/ wp-content/plugins/collectme/languages/collectme.pot --slug=collectme --domain=collectme --exclude=tmp,vendor --skip-js --skip-block-json --skip-theme-json'

      - name: Setup git config
        run: |
          git config user.name "GitHub Actions L10N"
          git config user.email "<>"

      - name: If translation template has changes
        run: >-
          (
          git diff -U0 
          | grep '^[+-]' 
          | grep -Ev '^(--- a/|\+\+\+ b/)' 
          | grep -v 'POT-Creation-Date:'
          | grep -v '^:#'
          && echo "CHANGES=1" >> $GITHUB_ENV
          ) 
          || true

      - name: Commit changed translation template
        run: |
          git add languages/collectme.pot
          git commit -m "[L10N] Update pot file"
          git push
        if: env.CHANGES

      - name: Sync with crowdin
        uses: crowdin/github-action@1.4.10
        with:
          upload_sources: true
          download_translations: true
          localization_branch_name: ${{ github.event.pull_request.head.ref }}
          skip_untranslated_strings: true
          export_only_approved: true
          create_pull_request: false
          push_translations: false
          config: crowdin.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

      - name: If translations have changed
        run: >-
          (
          git diff -U0 languages/*.po
          | grep '^[+-]' 
          | grep -Ev '^(--- a/|\+\+\+ b/)' 
          | grep -v 'POT-Creation-Date:'
          | grep -v 'PO-Revision-Date:'
          | grep -v '^:#'
          && echo "CHANGES=1" >> $GITHUB_ENV
          ) 
          || true

      - name: Generate mo files
        run: >-
          docker-compose 
          run 
          -u root:root
          --no-deps
          wordpress 
          bash 
          -c 'XDEBUG_MODE=off $(which wp) --allow-root i18n make-mo wp-content/plugins/collectme/languages'
        if: env.CHANGES

      - name: Commit changed translations
        run: |
          git add languages/*.{po,mo}
          git commit -m "[L10N] New translations from Crowdin"
          git push
        if: env.CHANGES
