on:
  push:
  workflow_call:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  add_test_deps:
    name: Add test dependencies files
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Install PHP dependencies with dev deps
        run: >-
          docker-compose 
          run 
          -u root:root 
          --no-deps
          wordpress 
          composer 
          --working-dir=wp-content/plugins/collectme 
          --no-interaction 
          install 
          --no-progress

      - name: Start MySQL
        run: >-
          docker-compose
          up
          -d
          mysql

      - name: Wait until MySQL is ready
        run: |
          while ! docker exec -t collectme_v2_mysql_1 sh -c 'mysql -uroot -e quit > /dev/null 2>&1'; do
            sleep 1
          done

      - name: Install WordPress test environment
        run: >-
          docker-compose 
          run
          -u root:root 
          wordpress
          bash
          -c 'cd wp-content/plugins/collectme && TMPDIR=$(pwd)/tmp bin/install-wp-tests.sh collectme_test root "" mysql latest'

  test_js:
    name: Run JS tests
    runs-on: ubuntu-latest
    needs:
      - add_test_deps
    steps:
      - name: TS check types
        run: >-
          docker-compose 
          run 
          -u root:root 
          --no-deps
          node 
          yarn 
          --no-progress 
          --non-interactive
          run
          type-check

      - name: Lint JS files
        run: >-
          docker-compose 
          run 
          -u root:root 
          --no-deps
          node 
          yarn 
          --no-progress 
          --non-interactive
          run
          lint

  test_php:
    name: Run PHP tests
    runs-on: ubuntu-latest
    needs:
      - add_test_deps
    steps:
      - name: PHP Unit
        run: >-
          docker-compose 
          run 
          -u root:root 
          wordpress 
          bash 
          -c 'cd wp-content/plugins/collectme && php vendor/bin/phpunit'
