on:
  push:
  workflow_call:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  php_tests:
    name: Run PHP tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Docker BuildX
        uses: docker/setup-buildx-action@v2

      - name: Build WordPress image
        uses: docker/build-push-action@v3
        with:
          context: .docker
          file: .docker/wordpress.Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          pull: true
          load: true

      - name: Install PHP dependencies with dev deps
        run: >-
          docker-compose 
          run 
          -u root:root 
          --no-deps
          wordpress 
          composer 
          --working-dir=wp-content/plugins/collectme 
          --no-interaction 
          install 
          --no-progress

      - name: Start MySQL
        run: >-
          docker-compose
          up
          -d
          mysql

      - name: Wait until MySQL is ready
        run: |
          while ! docker exec -t collectme_mysql_1 sh -c 'mysql -uroot -e quit > /dev/null 2>&1'; do
            sleep 1
          done

      - name: Install WordPress test environment
        run: >-
          docker-compose 
          run
          -u root:root 
          wordpress
          bash
          -c 'cd wp-content/plugins/collectme && TMPDIR=$(pwd)/tmp bin/install-wp-tests.sh collectme_test root "" mysql latest'

      - name: Run PHPUnit
        run: >-
          docker-compose 
          run 
          -u root:root 
          wordpress 
          bash 
          -c 'cd wp-content/plugins/collectme && php vendor/bin/phpunit'

  js_tests:
    name: Run JS tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: TS check types
        run: >-
          docker-compose 
          run 
          -u root:root 
          --no-deps
          node 
          yarn 
          --no-progress 
          --non-interactive
          run
          type-check

      - name: Lint JS files
        run: >-
          docker-compose 
          run 
          -u root:root 
          --no-deps
          node 
          yarn 
          --no-progress 
          --non-interactive
          run
          lint
